name: "0peration: Salvatore"

on:
  workflow_dispatch:
    inputs:
      STOCK_DEVICE:
        description: "Put the Model of your phone, remember it starts with SM-"
        required: true
        default: "SM-A325F"
      USE_UI_8_TETHERING_APEX:
        description: "Set True if your kernel BPF version is lower than 5.10"
        required: true
        default: "True"
      OUTPUT_FILESYSTEM:
        description: "OUTPUT_FILESYSTEM (erofs / ext4)"
        required: true
        default: "erofs"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
  
    - name: Cleaning junk files
      uses: rokibhasansagar/slimhub_actions@v25.42.5

    - name: Install required packages
      run: |
        sudo apt install -y \
          p7zip-full lz4 android-sdk-libsparse-utils \
          python3 python3-pip zipalign unzip default-jre openjdk-17-jdk brotli e2fsprogs
        pip3 install liblp tgcrypto pyrogram

        chmod +x bin/ext4/make_ext4fs
        chmod +x bin/erofs-utils/extract.erofs
        chmod +x bin/erofs-utils/mkfs.erofs

    - name: Setup directories
      run: |
        chmod +x scripts/setup_directories.sh
        bash scripts/setup_directories.sh FIRMWARE WORK OUT
    
    - name: Set build environment
      shell: bash
      run: |
        echo "STOCK_DEVICE=${{ github.event.inputs.STOCK_DEVICE }}" >> $GITHUB_ENV
        echo "USE_UI_8_TETHERING_APEX=${{ github.event.inputs.USE_UI_8_TETHERING_APEX }}" >> $GITHUB_ENV
        echo "OUTPUT_FILESYSTEM=${{ github.event.inputs.OUTPUT_FILESYSTEM }}" >> $GITHUB_ENV

        echo "OUT_DIR=$PWD/OUT" >> $GITHUB_ENV
        echo "WORK_DIR=$PWD/WORK" >> $GITHUB_ENV
        echo "FIRM_DIR=$PWD/FIRMWARE" >> $GITHUB_ENV
        echo "DEVICES_DIR=$PWD/0peration/Devices" >> $GITHUB_ENV
        echo "APKTOOL=$PWD/bin/apktool/apktool.jar" >> $GITHUB_ENV
        echo "VNDKS_COLLECTION=$PWD/0peration/vndks" >> $GITHUB_ENV
        echo "BUILD_PARTITIONS=product,vendor,odm,system_ext,system" >> $GITHUB_ENV

    - name: Download firmware
      shell: bash
      run: |
        source scripts/0peratn.sh
        source "$DEVICES_DIR/$STOCK_DEVICE/config"
        DOWNLOAD_FIRMWARE "$TARGET_DEVICE" "$FIRM_DIR"

    - name: Extract firmware
      shell: bash
      run: |
        source scripts/0peratn.sh
        EXTRACT_FIRMWARE "$FIRM_DIR/$TARGET_DEVICE"
        PREPARE_PARTITIONS "$FIRM_DIR/$TARGET_DEVICE"
        EXTRACT_FIRMWARE_IMG "$FIRM_DIR/$TARGET_DEVICE"

    - name: Apply vendor patches
      shell: bash
      run: |
        source scripts/0peratn.sh
        DISABLE_FBE "$FIRM_DIR/$TARGET_DEVICE"
        DISABLE_FDE "$FIRM_DIR/$TARGET_DEVICE"
        DELETE_ICCC "$FIRM_DIR/$TARGET_DEVICE"
        PATCH_FSTAB_EROFS "$FIRM_DIR/$TARGET_DEVICE"

    - name: Apply stock config
      shell: bash
      run: |
        source scripts/0peratn.sh
        APPLY_STOCK_CONFIG "$FIRM_DIR/$TARGET_DEVICE"

    - name: Debloat ROM
      shell: bash
      run: |
        source scripts/0peratn.sh
        DEBLOAT "$FIRM_DIR/$TARGET_DEVICE"

    - name: Apply features
      shell: bash
      run: |
        source scripts/0peratn.sh
        APPLY_FEATURES "$FIRM_DIR/$TARGET_DEVICE"

    - name: Update Build ID
      shell: bash
      run: |
        source scripts/0peratn.sh
        APPENDING_DISPLAY_ID "$FIRM_DIR/$TARGET_DEVICE"

    - name: Install stock framework-res
      shell: bash
      run: |
        source scripts/0peratn.sh
        INSTALL_FRAMEWORK \
          "$FIRM_DIR/$TARGET_DEVICE/system/system/framework/framework-res.apk"

    - name: Decompile framework jars
      shell: bash
      run: |
        source scripts/0peratn.sh
        DECOMPILE "$APKTOOL" \
          "$FIRM_DIR/$TARGET_DEVICE/system/system/framework/ssrm.jar" "$WORK_DIR"
        DECOMPILE "$APKTOOL" \
          "$FIRM_DIR/$TARGET_DEVICE/system/system/framework/services.jar" "$WORK_DIR"

    - name: Patch framework
      shell: bash
      run: |
        source scripts/0peratn.sh
        PATCH_SSRM "$WORK_DIR/ssrm"
        PATCH_KNOX_GUARD "$WORK_DIR/services"
        PATCH_FLAG_SECURE "$WORK_DIR/services"
        PATCH_SECURE_FOLDER "$WORK_DIR/services"

    - name: Recompile framework
      shell: bash
      run: |
        source scripts/0peratn.sh
        RECOMPILE "$APKTOOL" "$WORK_DIR/ssrm" \
          "$FIRM_DIR/$TARGET_DEVICE/system/system/framework" "$WORK_DIR"
        RECOMPILE "$APKTOOL" "$WORK_DIR/services" \
          "$FIRM_DIR/$TARGET_DEVICE/system/system/framework" "$WORK_DIR"
        cp -fv "$WORK_DIR"/*.jar \
          "$FIRM_DIR/$TARGET_DEVICE/system/system/framework/"

    - name: Build images
      shell: bash
      run: |
        source scripts/0peratn.sh
        BUILD_IMG "$FIRM_DIR/$TARGET_DEVICE" "$OUTPUT_FILESYSTEM" "$OUT_DIR"
        IMG_TO_SDAT_AND_COMPRESS "$OUT_DIR" "TMP"

    - name: Update updater-script
      shell: bash
      run: |
        # Variables
        ROM_VERSION="8.5.1"
        BUILD_DATE=$(date +'%d%m%Y')
        DEVICE="${{ github.event.inputs.STOCK_DEVICE }}"
        UPDATER_PATH="$(pwd)/template/META-INF/com/google/android/updater-script"

        if [[ "$DEVICE" == "SM-A325F" || "$DEVICE" == "SM-A325M" || "$DEVICE" == "SM-A325N" ]]; then
            DEVICE_CODENAME="a32"
            DISPLAY_NAME="Galaxy A32 4G"
        elif [[ "$DEVICE" == "SM-A225F" ]]; then
            DEVICE_CODENAME="a22"
            DISPLAY_NAME="Galaxy A22 4G"
        elif [[ "$DEVICE" == "SM-M325F" ]]; then
            DEVICE_CODENAME="m32"
            DISPLAY_NAME="Galaxy M32 4G"
        elif [[ "$DEVICE" == "SM-E225F" ]]; then
            DEVICE_CODENAME="f22"
            DISPLAY_NAME="Galaxy F22 4G"
        elif [[ "$DEVICE" == "SM-M225F" ]]; then
            DEVICE_CODENAME="m22"
            DISPLAY_NAME="Galaxy M22 4G"
        else
            DEVICE_CODENAME="unknown"
            DISPLAY_NAME="Unknown Device"
        fi

        NEW_CHECK="getprop(\"ro.boot.em.model\") == \"$DEVICE\" || abort(\"E3004: This package is for $DEVICE_CODENAME\");"

        echo "Updating device on updater-script for $DISPLAY_NAME..."
      
        sed -i "s!^getprop(\"ro.boot.em.model\").*!$NEW_CHECK!" "$UPDATER_PATH"

        sed -i "s!ui_print(\".*for .*\");!ui_print(\"        $ROM_VERSION-$BUILD_DATE for $DISPLAY_NAME\");!" "$UPDATER_PATH"

    - name: Prepare flashable zip
      shell: bash
      run: |
        # Variables
        ROM_VERSION="8.5.1"
        BUILD_DATE=$(date +'%d%m%Y')
        DEVICE="${{ github.event.inputs.STOCK_DEVICE }}"

        if [[ "$DEVICE" == "SM-A325F" || "$DEVICE" == "SM-A325M" || "$DEVICE" == "SM-A325N" ]]; then
            DEVICE_CODENAME="a32"
        elif [[ "$DEVICE" == "SM-A225F" ]]; then
            DEVICE_CODENAME="a22"
        elif [[ "$DEVICE" == "SM-M325F" ]]; then
            DEVICE_CODENAME="m32"
        elif [[ "$DEVICE" == "SM-E225F" ]]; then
            DEVICE_CODENAME="f22"
        elif [[ "$DEVICE" == "SM-M225F" ]]; then
            DEVICE_CODENAME="m22"
        else
            DEVICE_CODENAME="unknown"
        fi

        TEMPLATE_DIR="$(pwd)/template"
        mkdir -p "$TEMPLATE_DIR"

        SPECIFIC_BOOT="$(pwd)/0peration/Devices/$DEVICE/boot.img"

        if [ -f "$SPECIFIC_BOOT" ]; then
            echo "-> Copying boot.img from $DEVICE..."
            cp "$SPECIFIC_BOOT" "$TEMPLATE_DIR/boot.img"
        else
            echo "There is no boot.img for $DEVICE"
        fi

        echo "Copying compressed DAT files to template..."
        cp TMP/*.new.dat.br "$TEMPLATE_DIR"/
        cp TMP/*.patch.dat "$TEMPLATE_DIR"/
        cp TMP/*.transfer.list "$TEMPLATE_DIR"/ 2>/dev/null || true

        echo "Creating ZIP package..."
        ZIP_FILE="0peration_${ROM_VERSION}-${BUILD_DATE}_${DEVICE_CODENAME}.zip"
        [ -f "$ZIP_FILE" ] && rm "$ZIP_FILE"

        # ZIP the rom
        cd "$TEMPLATE_DIR"
        zip -r "$ZIP_FILE" ./*

        echo "ZIP package created: $ZIP_FILE"
        echo "ZIP_NAME=$ZIP_FILE" >> $GITHUB_ENV

    - name: Sending ROM to GoFile.
      run: |
          chmod +x ./upload.sh 
          bash ./upload.sh "$(pwd)/template/${{ env.ZIP_NAME }}"

    - name: Cleanup
      run: |
        rm -rf *
